function compile_msound_mac

eval(['mex ', ...
      '-output msound ' ...
      '-Dchar16_t=UINT16_T ' ...
      '-largeArrayDims ' ...
      '-I/usr/local/include ' ...
      '-I' matlabroot '/extern/include/ ' ...
      'LDFLAGS=''\$LDFLAGS -l portaudio'' ' ...
      'msound.c'])
