function compile_msound_mac

% Msound uses the open source library PortAudio which supports various
% operating systems and audio APIs. Mac OS X is completely build around a
% single audio API which is Core Audio. Therefore no selection of APIs
% exists for the Mac. This compile script relies on the PortAudio library
% being installed system-wide.

eval(['mex ', ...
      '-output msound ' ...
      '-Dchar16_t=UINT16_T ' ...
      '-largeArrayDims ' ...
      '-L/usr/local/lib ' ...
      '-lportaudio ' ...
      '-I/usr/local/include ' ...
      '-I' matlabroot '/extern/include/ ' ...
      'msound.c'])
